name: onvision

services:
  db:
    image: postgres:latest
    container_name: onvision-postgres

    env_file:
      - .env.dev
    environment:
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ko-KR --encoding=UTF8"
    ports:
      - "5432:5432"
    networks:
      - onvision_network
    volumes:
      - onvision-data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: onvision-redis
    ports:
      - "6379:6379"
    networks:
      - onvision_network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - onvision_network
    depends_on:
      - redis

volumes:
  onvision-data:
networks:
  onvision_network:
    driver: bridge