spring:
  application:
    name: vision
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.${spring.profiles.active}[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



jwt:
  validations:
    access: 900000
    refresh: 604800000
    register: 900000
  secrets:
    app-key: ${JWT_APP_KEY}
    origin-key: ${JWT_SECRET_KEY}
redis:
  expired:
    presence: 180  #초단위