springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info