spring:
  application:
    name: vision
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.${spring.profiles.active}[.properties]


jwt:
  validations:
    access: 900000
    refresh: 604800000
  secrets:
    app-key: ${JWT_APP_KEY}
    origin-key: ${JWT_SECRET_KEY}