springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    "mtvs.onvision.vision.presence": ${LOG_LEVEL_PRESENCE:info}
    "mtvs.onvision.vision.location": ${LOG_LEVEL_LOCATION:info}
    "mtvs.onvision.vision.navigation": ${LOG_LEVEL_NAVIGATION:info}
    "mtvs.onvision.vision.favorite": ${LOG_LEVEL_FAVORITE:info}
    "mtvs.onvision.vision.command": ${LOG_LEVEL_COMMAND:info}
    "mtvs.onvision.vision.auth": ${LOG_LEVEL_AUTH:info}
    "org.hibernate.SQL": ${LOG_LEVEL_SQL:info}

server:
  forward-headers-strategy: framework