spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: false          # clean 허용

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui
    display-request-duration: true
    doc-expansion: list
    persist-authorization: true