CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE alert_deliveries
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    status        VARCHAR(20)                             NOT NULL,
    alert_id      BIGINT                                  NOT NULL,
    fid           VARCHAR(255)                            NOT NULL,
    attempt_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_alert_deliveries PRIMARY KEY (id)
);

CREATE TABLE alerts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    type        VARCHAR(20)                             NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    address     VARCHAR(100),
    s3_key      VARCHAR(100),
    occurred_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    action      VARCHAR(255),
    sender_id   BIGINT,
    CONSTRAINT pk_alerts PRIMARY KEY (id)
);

CREATE TABLE favorites
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(50)                             NOT NULL,
    nickname     VARCHAR(50),
    pkey         VARCHAR(50)                             NOT NULL,
    land_address VARCHAR(100)                            NOT NULL,
    road_address VARCHAR(100)                            NOT NULL,
    latitude     DOUBLE PRECISION                        NOT NULL,
    longitude    DOUBLE PRECISION                        NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_favorites PRIMARY KEY (id)
);

CREATE TABLE fids
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    fid        VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    CONSTRAINT pk_fids PRIMARY KEY (id)
);

CREATE TABLE location_histories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_location_histories PRIMARY KEY (id)
);

CREATE TABLE relations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    ward_id     BIGINT                                  NOT NULL,
    guardian_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_relations PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE routes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    starting_name       VARCHAR(50)                             NOT NULL,
    starting_address    VARCHAR(100)                            NOT NULL,
    starting_lat        DOUBLE PRECISION                        NOT NULL,
    starting_lon        DOUBLE PRECISION                        NOT NULL,
    destination_name    VARCHAR(50)                             NOT NULL,
    destination_address VARCHAR(100)                            NOT NULL,
    destination_lat     DOUBLE PRECISION                        NOT NULL,
    destination_lon     DOUBLE PRECISION                        NOT NULL,
    status              VARCHAR(255)                            NOT NULL,
    total_distance      INTEGER                                 NOT NULL,
    total_time          INTEGER                                 NOT NULL,
    mode                VARCHAR(255)                            NOT NULL,
    report              TEXT                                    NOT NULL,
    ward_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    nickname     VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE fids
    ADD CONSTRAINT uc_fids_fid UNIQUE (fid);

ALTER TABLE relations
    ADD CONSTRAINT uc_relations_guardian UNIQUE (guardian_id);

ALTER TABLE relations
    ADD CONSTRAINT uc_relations_ward UNIQUE (ward_id);

-- soft 삭제
CREATE UNIQUE INDEX uix_users_email_active
    ON users (email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uix_users_phone_active
    ON users (phone_number) WHERE deleted_at IS NULL;

ALTER TABLE alert_deliveries
    ADD CONSTRAINT uk_alert_delivery UNIQUE (alert_id, fid);

CREATE INDEX idx_alert_delivery_status ON alert_deliveries (status);

ALTER TABLE alerts
    ADD CONSTRAINT FK_ALERTS_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE alert_deliveries
    ADD CONSTRAINT FK_ALERT_DELIVERIES_ON_ALERT FOREIGN KEY (alert_id) REFERENCES alerts (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE fids
    ADD CONSTRAINT FK_FIDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_GUARDIAN FOREIGN KEY (guardian_id) REFERENCES users (id);

ALTER TABLE relations
    ADD CONSTRAINT FK_RELATIONS_ON_WARD FOREIGN KEY (ward_id) REFERENCES users (id);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_WARD FOREIGN KEY (ward_id) REFERENCES users (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);