CREATE TABLE commands
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    type        VARCHAR(20)                             NOT NULL,
    receiver_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_commands PRIMARY KEY (id)
);

ALTER TABLE commands
    ADD CONSTRAINT FK_COMMANDS_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES users (id);