CREATE TABLE instructions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instruction VARCHAR(255)                            NOT NULL,
    guardian_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_instructions PRIMARY KEY (id)
);

ALTER TABLE instructions
    ADD CONSTRAINT FK_INSTRUCTIONS_ON_GUARDIAN FOREIGN KEY (guardian_id) REFERENCES users (id);